[package]
name = "constrained_scheduling"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toy-blif-parser = { path = "../toy-blif-parser", version = "0.3.0" }
